---
- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /opt/anaconda3/bin/python

  tasks:
    - name: Pull image
      docker_image:
        name: mayank8529/calculator:latest
        source: pull

    - name: Remove existing container if it exists
      shell: |
        if [ "$(docker ps -a -q -f name=Calculator)" ]; then
          docker rm -f Calculator
        fi

    - name: Running container
      shell: docker run -it -d --name Calculator mayank8529/calculator
