#The purpose of this playbook is to automate the deployment of the calculator Docker image on a host machine.
#It handles pulling the latest version of the image, ensuring that any previously running instance of the container is removed,
#and then starting the new container in a clean state.
#      Executes shell commands. Here, it checks if a Docker container named "Calculator" already exists (docker ps -a -q -f name=Calculator),
#  and if it does, it removes it (docker rm -f Calculator).
#  This ensures that any existing container with the same name is deleted before a new one is created.
---
- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /opt/anaconda3/bin/python

  tasks:
    - name: Pull image
      docker_image:
        name: mayank8529/calculator:latest
        source: pull

    - name: Remove existing container if it exists
      shell: |
        if [ "$(docker ps -a -q -f name=Calculator)" ]; then
          docker rm -f Calculator
        fi

    - name: Running container
      shell: docker run -it -d --name Calculator mayank8529/calculator
